echo "GPG"
echo "SSH keys"
echo "Keybase/GPG Keychain"
echo "Grammar.ly"
echo "hyper switch"
echo "alfred"
echo "uto..."
echo "Office"
echo "intellij"
echo "phpstorm/intellij config"
echo "Pathfinder"
